1
0
Error: Variable name 'true' can't be reserved word.
Error: Variable name 'false' can't be reserved word.
Error: Parameter name 'true' can't be reserved word.
Error: Parameter name 'true' can't be reserved word.
Error: Parameter name 'call' can't be reserved word.
Error: Closing bracket is missing.
Error: Closing bracket can't be before an opening one.
Error: Closing bracket can't be before an opening one.
g4(x) := (x + 1)
g5(x) := (x + 1)
g6(x) := (x + ((x -> 1) & 1))
var(x) := x
Error: Variable 'var' is already declared.
var(x) := x
