f_true := 1
-----------
|| f_true |
-----------
||      1 |
-----------
f(x, y, z) := ((x & y) -> z)
---------------------------
| x | y | z || f(x, y, z) |
---------------------------
| 0 | 0 | 0 ||          1 |
| 0 | 0 | 1 ||          1 |
| 0 | 1 | 0 ||          1 |
| 0 | 1 | 1 ||          1 |
| 1 | 0 | 0 ||          1 |
| 1 | 0 | 1 ||          1 |
| 1 | 1 | 0 ||          0 |
| 1 | 1 | 1 ||          1 |
---------------------------
Error: Parameter 'unknown' of function 'table' must be an existing variable name.
Error: Incorrect amount of parameters during call of function 'table'. Expected amount - 1, actual amount - 2.
